# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'caijunhui/trading-plus'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        latest
        $(Build.BuildId)
